# Generated by Django 4.1.3 on 2022-11-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filePath", models.CharField(max_length=100)),
                ("businessName", models.CharField(max_length=100)),
                ("invoiceDate", models.CharField(max_length=50)),
                ("invoiceTotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("invoiceText", models.TextField()),
            ],
            options={
                "db_table": "receipts",
            },
        ),
    ]
