# Generated by Django 4.1.3 on 2022-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts_processing", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="filePath",
            new_name="file_path",
        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="businessName",
            new_name="business_name",

        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="invoiceDate",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="invoiceText",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="invoiceTotal",
            new_name="total",
        )

    ]
