# Generated by Django 4.1.3 on 2022-11-24 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("receipts_processing", "0003_remove_receipt_file_path_receipt_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="receipt",
            name="business_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="date",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
