# Generated by Django 4.1.3 on 2022-11-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "receipts_processing",
            "0004_receipt_created_at_alter_receipt_business_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="filename",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
