# Generated by Django 4.1.3 on 2022-12-09 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts_processing", "0006_receipt_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="date",
            field=models.DateField(default=datetime.date(2022, 12, 9)),
            preserve_default=False,
        ),
    ]
